import { MigrationInterface, QueryRunner } from 'typeorm'

export class Generate1729923478104 implements MigrationInterface {
  name = 'Generate1729923478104'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`user_refresh_tokens\` DROP FOREIGN KEY \`FK_1dfd080c2abf42198691b60ae39\``)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` DROP FOREIGN KEY \`FK_e9d9d0c303432e4e5e48c1c3e90\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP FOREIGN KEY \`FK_c75280b01c49779f2323536db67\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP FOREIGN KEY \`FK_96bde34263e2ae3b46f011124ac\``)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP FOREIGN KEY \`FK_9cb7989853c4cb7fe427db4b260\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP FOREIGN KEY \`FK_d68ea74fcb041c8cfd1fd659844\``)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP FOREIGN KEY \`FK_3029712e0df6a28edaee46fd470\``)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP FOREIGN KEY \`FK_f4d9c36052fdb188ff5c089454b\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP FOREIGN KEY \`FK_2b95fdc95b329d66c18f5baed6d\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP FOREIGN KEY \`FK_6d61c5b3f76a3419d93a4216695\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` ADD \`user_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`parentId\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`parentId\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP FOREIGN KEY \`FK_35ce749b04d57e226d059e0f633\``)
    await queryRunner.query(`ALTER TABLE \`sys_role\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` CHANGE \`value\` \`value\` varchar(255) NOT NULL COMMENT '角色标识'`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP FOREIGN KEY \`FK_96311d970191a044ec048011f44\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP COLUMN \`dept_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD \`dept_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`todo\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD \`user_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` CHANGE \`create_by\` \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` CHANGE \`update_by\` \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` CHANGE \`create_by\` \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` CHANGE \`update_by\` \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`type_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`type_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_config\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_config\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_config\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_config\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_task\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_task\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_task\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_task\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD \`user_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` CHANGE \`id\` \`id\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD \`id\` bigint NOT NULL PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP COLUMN \`task_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD \`task_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`menu_id\`)`)
    await queryRunner.query(`DROP INDEX \`IDX_35ce749b04d57e226d059e0f63\` ON \`sys_role_menus\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP COLUMN \`role_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD \`role_id\` bigint NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`menu_id\`, \`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`role_id\`)`)
    await queryRunner.query(`DROP INDEX \`IDX_2b95fdc95b329d66c18f5baed6\` ON \`sys_role_menus\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP COLUMN \`menu_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD \`menu_id\` bigint NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`role_id\`, \`menu_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`role_id\`)`)
    await queryRunner.query(`DROP INDEX \`IDX_96311d970191a044ec048011f4\` ON \`sys_user_roles\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD \`user_id\` bigint NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`role_id\`, \`user_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`user_id\`)`)
    await queryRunner.query(`DROP INDEX \`IDX_6d61c5b3f76a3419d93a421669\` ON \`sys_user_roles\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP COLUMN \`role_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD \`role_id\` bigint NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`user_id\`, \`role_id\`)`)
    await queryRunner.query(`CREATE INDEX \`IDX_35ce749b04d57e226d059e0f63\` ON \`sys_role_menus\` (\`role_id\`)`)
    await queryRunner.query(`CREATE INDEX \`IDX_2b95fdc95b329d66c18f5baed6\` ON \`sys_role_menus\` (\`menu_id\`)`)
    await queryRunner.query(`CREATE INDEX \`IDX_96311d970191a044ec048011f4\` ON \`sys_user_roles\` (\`user_id\`)`)
    await queryRunner.query(`CREATE INDEX \`IDX_6d61c5b3f76a3419d93a421669\` ON \`sys_user_roles\` (\`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`user_refresh_tokens\` ADD CONSTRAINT \`FK_1dfd080c2abf42198691b60ae39\` FOREIGN KEY (\`accessTokenId\`) REFERENCES \`user_access_tokens\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` ADD CONSTRAINT \`FK_e9d9d0c303432e4e5e48c1c3e90\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD CONSTRAINT \`FK_c75280b01c49779f2323536db67\` FOREIGN KEY (\`parentId\`) REFERENCES \`sys_dept\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD CONSTRAINT \`FK_96bde34263e2ae3b46f011124ac\` FOREIGN KEY (\`dept_id\`) REFERENCES \`sys_dept\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD CONSTRAINT \`FK_9cb7989853c4cb7fe427db4b260\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD CONSTRAINT \`FK_3029712e0df6a28edaee46fd470\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD CONSTRAINT \`FK_f4d9c36052fdb188ff5c089454b\` FOREIGN KEY (\`task_id\`) REFERENCES \`sys_task\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD CONSTRAINT \`FK_35ce749b04d57e226d059e0f633\` FOREIGN KEY (\`role_id\`) REFERENCES \`sys_role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD CONSTRAINT \`FK_2b95fdc95b329d66c18f5baed6d\` FOREIGN KEY (\`menu_id\`) REFERENCES \`sys_menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD CONSTRAINT \`FK_96311d970191a044ec048011f44\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD CONSTRAINT \`FK_6d61c5b3f76a3419d93a4216695\` FOREIGN KEY (\`role_id\`) REFERENCES \`sys_role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP FOREIGN KEY \`FK_6d61c5b3f76a3419d93a4216695\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP FOREIGN KEY \`FK_96311d970191a044ec048011f44\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP FOREIGN KEY \`FK_2b95fdc95b329d66c18f5baed6d\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP FOREIGN KEY \`FK_35ce749b04d57e226d059e0f633\``)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP FOREIGN KEY \`FK_f4d9c36052fdb188ff5c089454b\``)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP FOREIGN KEY \`FK_3029712e0df6a28edaee46fd470\``)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP FOREIGN KEY \`FK_9cb7989853c4cb7fe427db4b260\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP FOREIGN KEY \`FK_96bde34263e2ae3b46f011124ac\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP FOREIGN KEY \`FK_c75280b01c49779f2323536db67\``)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` DROP FOREIGN KEY \`FK_e9d9d0c303432e4e5e48c1c3e90\``)
    await queryRunner.query(`ALTER TABLE \`user_refresh_tokens\` DROP FOREIGN KEY \`FK_1dfd080c2abf42198691b60ae39\``)
    await queryRunner.query(`DROP INDEX \`IDX_6d61c5b3f76a3419d93a421669\` ON \`sys_user_roles\``)
    await queryRunner.query(`DROP INDEX \`IDX_96311d970191a044ec048011f4\` ON \`sys_user_roles\``)
    await queryRunner.query(`DROP INDEX \`IDX_2b95fdc95b329d66c18f5baed6\` ON \`sys_role_menus\``)
    await queryRunner.query(`DROP INDEX \`IDX_35ce749b04d57e226d059e0f63\` ON \`sys_role_menus\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`user_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP COLUMN \`role_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD \`role_id\` int NOT NULL`)
    await queryRunner.query(`CREATE INDEX \`IDX_6d61c5b3f76a3419d93a421669\` ON \`sys_user_roles\` (\`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`role_id\`, \`user_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD \`user_id\` int NOT NULL`)
    await queryRunner.query(`CREATE INDEX \`IDX_96311d970191a044ec048011f4\` ON \`sys_user_roles\` (\`user_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD PRIMARY KEY (\`role_id\`, \`user_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP COLUMN \`menu_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD \`menu_id\` int NOT NULL`)
    await queryRunner.query(`CREATE INDEX \`IDX_2b95fdc95b329d66c18f5baed6\` ON \`sys_role_menus\` (\`menu_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`menu_id\`, \`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`menu_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP COLUMN \`role_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD \`role_id\` int NOT NULL`)
    await queryRunner.query(`CREATE INDEX \`IDX_35ce749b04d57e226d059e0f63\` ON \`sys_role_menus\` (\`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` DROP PRIMARY KEY`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD PRIMARY KEY (\`menu_id\`, \`role_id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP COLUMN \`task_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD \`task_id\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_captcha_log\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD \`user_id\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`tool_storage\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_task\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_task\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_task\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_task\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_config\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_config\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_config\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_config\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`type_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`type_id\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` CHANGE \`update_by\` \`update_by\` int NOT NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` CHANGE \`create_by\` \`create_by\` int NOT NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` CHANGE \`update_by\` \`update_by\` int NOT NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` CHANGE \`create_by\` \`create_by\` int NOT NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD \`user_id\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`todo\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`todo\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP COLUMN \`dept_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD \`dept_id\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD CONSTRAINT \`FK_96311d970191a044ec048011f44\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` CHANGE \`value\` \`value\` varchar(255) COLLATE "utf8mb4_general_ci" NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD CONSTRAINT \`FK_35ce749b04d57e226d059e0f633\` FOREIGN KEY (\`role_id\`) REFERENCES \`sys_role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`parentId\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`parentId\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD PRIMARY KEY (\`id\`)`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` DROP COLUMN \`user_id\``)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` ADD \`user_id\` int NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_user_roles\` ADD CONSTRAINT \`FK_6d61c5b3f76a3419d93a4216695\` FOREIGN KEY (\`role_id\`) REFERENCES \`sys_role\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`sys_role_menus\` ADD CONSTRAINT \`FK_2b95fdc95b329d66c18f5baed6d\` FOREIGN KEY (\`menu_id\`) REFERENCES \`sys_menu\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`sys_task_log\` ADD CONSTRAINT \`FK_f4d9c36052fdb188ff5c089454b\` FOREIGN KEY (\`task_id\`) REFERENCES \`sys_task\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`sys_login_log\` ADD CONSTRAINT \`FK_3029712e0df6a28edaee46fd470\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD CONSTRAINT \`FK_d68ea74fcb041c8cfd1fd659844\` FOREIGN KEY (\`type_id\`) REFERENCES \`sys_dict_type\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`todo\` ADD CONSTRAINT \`FK_9cb7989853c4cb7fe427db4b260\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`sys_user\` ADD CONSTRAINT \`FK_96bde34263e2ae3b46f011124ac\` FOREIGN KEY (\`dept_id\`) REFERENCES \`sys_dept\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD CONSTRAINT \`FK_c75280b01c49779f2323536db67\` FOREIGN KEY (\`parentId\`) REFERENCES \`sys_dept\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`user_access_tokens\` ADD CONSTRAINT \`FK_e9d9d0c303432e4e5e48c1c3e90\` FOREIGN KEY (\`user_id\`) REFERENCES \`sys_user\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`)
    await queryRunner.query(`ALTER TABLE \`user_refresh_tokens\` ADD CONSTRAINT \`FK_1dfd080c2abf42198691b60ae39\` FOREIGN KEY (\`accessTokenId\`) REFERENCES \`user_access_tokens\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`)
  }
}
