import { MigrationInterface, QueryRunner } from 'typeorm'

export class Generate1731470224279 implements MigrationInterface {
  name = 'Generate1731470224279'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_70f6de2aa6c35558e11a8f2a78e\``)
    await queryRunner.query(`CREATE TABLE \`sys_img_ai\` (\`id\` bigint NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`model\` tinyint NOT NULL COMMENT '模型名称' DEFAULT '1', \`img_ai_url\` varchar(255) NULL COMMENT '图片链接', \`order_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`)
    await queryRunner.query(`CREATE TABLE \`sys_img_template\` (\`id\` bigint NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(50) NOT NULL, \`type\` tinyint NOT NULL DEFAULT '1', \`status\` tinyint NOT NULL DEFAULT '1', \`remark\` varchar(255) NULL, \`template_url\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`)
    await queryRunner.query(`CREATE TABLE \`sys_img_bundles\` (\`id\` bigint NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(50) NOT NULL, \`price\` int NOT NULL, \`status\` tinyint NOT NULL DEFAULT '1', \`remark\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`)
    await queryRunner.query(`CREATE TABLE \`sys_bundles_template\` (\`img_bundles_id\` bigint NOT NULL, \`img_template_id\` bigint NOT NULL, INDEX \`IDX_17776b68c87ae20b75550ad7e9\` (\`img_bundles_id\`), INDEX \`IDX_9b7dfb4bd7122c1f86ead22412\` (\`img_template_id\`), PRIMARY KEY (\`img_bundles_id\`, \`img_template_id\`)) ENGINE=InnoDB`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_role\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`create_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`update_by\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`order\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`orderNo\``)
    await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`clinet_user_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`order_no\` int NULL COMMENT '字典项排序'`)
    await queryRunner.query(`ALTER TABLE \`order\` ADD \`client_user_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`amount\``)
    await queryRunner.query(`ALTER TABLE \`order\` ADD \`amount\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`payed\``)
    await queryRunner.query(`ALTER TABLE \`order\` ADD \`payed\` int NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_img_ai\` ADD CONSTRAINT \`FK_fe38c2d030202fb4abf19868132\` FOREIGN KEY (\`order_id\`) REFERENCES \`order\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_d36b5ccb52bbe47dc802c8e0a78\` FOREIGN KEY (\`client_user_id\`) REFERENCES \`client_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await queryRunner.query(`ALTER TABLE \`sys_bundles_template\` ADD CONSTRAINT \`FK_17776b68c87ae20b75550ad7e9f\` FOREIGN KEY (\`img_bundles_id\`) REFERENCES \`sys_img_bundles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`)
    await queryRunner.query(`ALTER TABLE \`sys_bundles_template\` ADD CONSTRAINT \`FK_9b7dfb4bd7122c1f86ead22412e\` FOREIGN KEY (\`img_template_id\`) REFERENCES \`sys_img_template\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`sys_bundles_template\` DROP FOREIGN KEY \`FK_9b7dfb4bd7122c1f86ead22412e\``)
    await queryRunner.query(`ALTER TABLE \`sys_bundles_template\` DROP FOREIGN KEY \`FK_17776b68c87ae20b75550ad7e9f\``)
    await queryRunner.query(`ALTER TABLE \`order\` DROP FOREIGN KEY \`FK_d36b5ccb52bbe47dc802c8e0a78\``)
    await queryRunner.query(`ALTER TABLE \`sys_img_ai\` DROP FOREIGN KEY \`FK_fe38c2d030202fb4abf19868132\``)
    await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`payed\``)
    await queryRunner.query(`ALTER TABLE \`order\` ADD \`payed\` decimal NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`amount\``)
    await queryRunner.query(`ALTER TABLE \`order\` ADD \`amount\` decimal NOT NULL`)
    await queryRunner.query(`ALTER TABLE \`order\` DROP COLUMN \`client_user_id\``)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` DROP COLUMN \`order_no\``)
    await queryRunner.query(`ALTER TABLE \`order\` ADD \`clinet_user_id\` bigint NULL`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`orderNo\` int NULL COMMENT '字典项排序'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`order\` int NULL COMMENT '字典项排序'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_item\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dict_type\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_role\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_menu\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`update_by\` int NULL COMMENT '更新者'`)
    await queryRunner.query(`ALTER TABLE \`sys_dept\` ADD \`create_by\` int NULL COMMENT '创建者'`)
    await queryRunner.query(`DROP INDEX \`IDX_9b7dfb4bd7122c1f86ead22412\` ON \`sys_bundles_template\``)
    await queryRunner.query(`DROP INDEX \`IDX_17776b68c87ae20b75550ad7e9\` ON \`sys_bundles_template\``)
    await queryRunner.query(`DROP TABLE \`sys_bundles_template\``)
    await queryRunner.query(`DROP TABLE \`sys_img_bundles\``)
    await queryRunner.query(`DROP TABLE \`sys_img_template\``)
    await queryRunner.query(`DROP TABLE \`sys_img_ai\``)
    await queryRunner.query(`ALTER TABLE \`order\` ADD CONSTRAINT \`FK_70f6de2aa6c35558e11a8f2a78e\` FOREIGN KEY (\`clinet_user_id\`) REFERENCES \`client_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }
}
